# change prefix to ctrl+a
unbind C-b
set-option -g prefix C-a

# set mouse support
set -g mouse on

# set terminal colors
set -g default-terminal "tmux-256color"

# split panes using | and -
bind = split-window -h
bind - split-window -v
unbind '"'
unbind '%'

# split panes open on current dir
bind = split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# change panes with alt-(hjkl)
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# remove ESC key delay
set -s escape-time 0

# start pane count at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# reload conf
bind r source-file ~/.tmux.conf \; display "Config reloaded!"
